CREATE TABLE Genres(
  ID INT PRIMARY KEY,
  TITLE VARCHAR(255)
);

CREATE TABLE Movies(
  ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  GEN_ID INT,
  DESCRIPTION VARCHAR(255),
  LENGTH INT,
  RELEASE_YEAR INT,
  FOREIGN KEY(GEN_ID) REFERENCES Genres(ID)
);

CREATE TABLE Theatres(
  ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  ADDRESS VARCHAR(255),
  ZIP INT
);

CREATE TABLE Ratings(
  MID INT,
  REVIEWER VARCHAR(255),
  STAR FLOAT,
  REV_DATE DATE,
  FOREIGN KEY(MID) REFERENCES Movies(ID) ON DELETE CASCADE,
  PRIMARY KEY(MID, REVIEWER)
);

CREATE TABLE Ticket_Sell(
  SERIAL_ID INT PRIMARY KEY,
  MID INT,
  TID INT,
  START_TIME DATETIME,
  PRICE FLOAT,
  TYPE VARCHAR(255),
  FOREIGN KEY(MID) REFERENCES Movies(ID) ON DELETE CASCADE,
  FOREIGN KEY(TID) REFERENCES Theatres(ID)
);

CREATE TABLE Movie_Cast(
  ACT_ID INT,
  MID INT,
  NAME VARCHAR(255),
  ROLE VARCHAR(255),
  FOREIGN KEY(MID) REFERENCES Movies(ID) ON DELETE CASCADE,
  PRIMARY KEY(ACT_ID, MID)
);
